backend:
  name: github
  repo: davidamosbanda/share-love-ministry
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Status", name: "status", widget: "select", options: ["Past", "Ongoing", "Upcoming"]}
      - {label: "Short Summary", name: "summary", widget: "text"}
      - {label: "Full Description", name: "body", widget: "markdown"}
      - {label: "Project Photo", name: "image", widget: "image"}

  - name: "homepage"
    label: "Home Page Slider"
    delete: false
    files:
      - label: "Slider Images"
        name: "slider"
        file: "_content/slider.json"
        fields:
          - label: "Photos"
            name: "slides"
            widget: "list"
            fields:
              - {label: "Upload Photo", name: "image", widget: "image"}
              - {label: "Photo Description", name: "alt", widget: "string", required: false}
